apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  clientId: {{ .Values.global.azure.identity.clientId | quote }}
  planId: {{ .Values.global.azure.marketplace.planId |quote}}
  resourceId: {{ .Values.global.azure.extension.resourceId | quote}}
