apiVersion: apps/v1
kind: Deployment
metadata:
  name: bci-base
  labels:
    app: bci-base
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: bci-base-{{ .Release.Name }}
        image: "{{ .Values.global.azure.images.base.registry }}/{{ .Values.global.azure.images.base.image }}@{{ .Values.global.azure.images.base.digest }}"
        command: ['sh', '-c', 'echo Have a lot of fun! && sleep 3600']
    metadata:
      labels:
        app: bci-base
        azure-extensions-usage-release-identifier: {{ .Release.Name }}
  selector:
    matchLabels:
      app: bci-base
